# #####################################################################################
#
# BATHROOM
#
# #####################################################################################
# Bathroom Fan - On Manual
# ##################################
- alias: bathroom_fan_on_manual
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001b94abe_action
      to: 'single'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.sonoff_4ch_relay_3
              state: 'on'
          sequence:
            - service: switch.turn_off
              entity_id: switch.sonoff_4ch_relay_3
        - conditions:
            - condition: state
              entity_id: switch.sonoff_4ch_relay_3
              state: 'off'
          sequence:
            - service: switch.turn_on
              entity_id: switch.sonoff_4ch_relay_3
            - delay: '00:10:00'
            - service: switch.turn_off
              entity_id: switch.sonoff_4ch_relay_3

# ##################################
# Bathroom Fan - Fans - Off
# ##################################
- alias: bathroom_fans_auto
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: '/2'
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ (states('sensor.0x158d00020d7c3a_humidity')|int - states('sensor.humidity_average')|int) <= 5 and is_state('switch.sonoff_4ch_relay_3','on') }}"
          sequence:
            - service: switch.turn_off
              entity_id: switch.sonoff_4ch_relay_3, switch.0x158d0002482619_switch
        - conditions:
            - condition: template
              value_template: "{{ ((states('sensor.0x158d00020d7c3a_humidity')|int - states('sensor.humidity_average')|int) >= 10) and (is_state('switch.0x4cf8cdf3c7a9a48_channel_2','off') and is_state('light.mirror_light_b','off')) and is_state('switch.sonoff_4ch_relay_3','off') }}"
          sequence:
            - service: switch.turn_on
              entity_id: switch.sonoff_4ch_relay_3, switch.0x158d0002482619_switch

# ##################################
# Bathroom - Bottom Fan On
# ##################################
- alias: bathroom_bottom_fan
  initial_state: 'true'
  trigger:
    - platform: time
      at: '07:00:03'
    - platform: time
      at: '23:00:03'
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'off'
  action:
    - service_template: "switch.turn_{%if states('binary_sensor.tod_day')%}off{%else%}on{%endif%}"
      data:
        entity_id: switch.0x158d0002482619_switch

# ##################################
# Bathroom - Bottom Fan
# ##################################
- alias: bathroom_bottom_fan_manual
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001b94abe_action
      to: 'double'
  action:
    - service: switch.toggle
      entity_id: switch.0x158d0002482619_switch
      
# ##################################
# Bathroom - Bottom Fan Toggle
# ##################################
- alias: bathroom_bottom_fan_toggle
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: input_boolean.security_mode
        state: 'off'
  action:
    - service: switch.toggle
      entity_id: switch.0x158d0002482619_switch