# ##################################
# System - Auto Lights Off - Family not home
# ##################################
- alias: system_auto_light_off_family_not_home
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.family_home
      to: "off"
      for: "00:00:10"
    - platform: state
      entity_id: binary_sensor.family_home
      to: "off"
    - platform: state
      entity_id: binary_sensor.family_home
      to: "not_home"
      for: "00:00:10"
    - platform: state
      entity_id: binary_sensor.family_home
      to: "not_home"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F3e2 Никого нет дома, выключаем освещение!"
    - service: script.lights_off
    - service: notify.telegram
      data_template:
        message: "\U0001f514 Освещение выключено! Режим охраны включен!"
    - service: input_boolean.turn_on
      entity_id: input_boolean.security_mode


# ##################################
# System - Security on - Sensors State change
# ##################################
- alias: system_security_sensors_state_change
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: sensor.security_last_change
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'on'
  action:
    - service: notify.ios_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "\U0001f46e Обнаружено движение! {{states.sensor.security_last_change.state}}"
    - service: notify.telegram_errors
      data_template:
        message: "\U0001f46e Внимание! Обнаружено движение! {{states.sensor.security_last_change.state}} "


# ##################################
# System - Family back home
# ##################################
- alias: system_family_back_home
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.family_home
      to: "on"
      for: "00:00:10"
    - platform: state
      entity_id: binary_sensor.family_home
      to: "on"
    - platform: state
      entity_id: binary_sensor.family_home
      to: "home"
      for: "00:00:10"
    - platform: state
      entity_id: binary_sensor.family_home
      to: "home"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f515 Режим охраны выключен!"
    - service: input_boolean.turn_off
      entity_id: input_boolean.security_mode