# ##################################
# System - Security on - Sensors State change
# ##################################
- alias: system_security_sensors_state_change
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00025371f6, binary_sensor.door_window_sensor_158d000200ad58, binary_sensor.door_window_sensor_158d00022ccffe, binary_sensor.door_window_sensor_158d00025370d1, binary_sensor.door_window_sensor_158d00027129ae, binary_sensor.door_window_sensor_158d0001ef2ffc, binary_sensor.door_window_sensor_158d0002a14c5e, binary_sensor.door_window_sensor_158d0002529b9c, binary_sensor.door_window_sensor_158d00025315e9, binary_sensor.door_window_sensor_158d0001e5d6be, binary_sensor.door_window_sensor_158d0002531749, binary_sensor.motion_sensor_158d0001e53cda, binary_sensor.motion_sensor_158d000224f89f, binary_sensor.motion_sensor_158d000236bb94, binary_sensor.motion_sensor_158d0001e05856, binary_sensor.motion_sensor_158d0002b482e9, binary_sensor.motion_sensor_158d0001d5995e, binary_sensor.motion_sensor_158d0001ae9f61, binary_sensor.motion_sensor_158d0002b4729d, binary_sensor.motion_sensor_158d000236bc6d, binary_sensor.motion_sensor_158d0001e54280, binary_sensor.motion_sensor_158d0001aea602, binary_sensor.unifi_motion_entrance, binary_sensor.unifi_motion_hall, binary_sensor.unifi_motion_kitchen
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'on'
  action:
    - service: notify.ios_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Обнаружено движение!"
    - service: notify.telegram
      data_template:
        message: "\U0000274c Внимание! Обнаружено движение!"

# ##################################
# System - Auto Lights Off - Family not home
# ##################################
- alias: system_auto_light_off_family_not_home
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.family
    from: "home"
    to: "not_home"
    for: "00:00:10"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F3e2 Никого нет дома, выключаем освещение!"
    - service: script.lights_off
    - service: notify.telegram
      data_template:
        message: "\U0001f514 Освещение выключено! Режим охраны включен!"
    - service: input_boolean.turn_on
      entity_id: input_boolean.security_mode

# ##################################
# System - Security - motion
# ##################################
- alias: system_security_motion
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_internal
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'on'
  action:
    - service: notify.ios_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Обнаружено движение!"
    - service: notify.telegram
      data_template:
        message: "\U0000274c Внимание! Обнаружено движение!"


# ##################################
# System - Family back home
# ##################################
- alias: system_family_back_home
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.family
    from: "not_home"
    to: "home"
    for: "00:00:01"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f515 Режим охраны выключен!"
    - service: input_boolean.turn_off
      entity_id: input_boolean.security_mode