# #####################################################################################
#
# HALL SMALL  - Lights
#
# #####################################################################################
# Hall Small - Auto Light On
# ##################################
- alias: hall_small_auto_night_light
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001ae9f61_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x158d0002b43ad4_motion
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: light.round_led_hs
        state: 'off'
      - condition: state
        entity_id: light.btf_pixel_strip_top
        state: 'off'
      - condition: state
        entity_id: light.round_led_k
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.btf_pixel_strip_top
      data:
        brightness_pct: 45
        rgb_color: [255, 180, 107]
    - delay: '00:00:30'
    - service: light.turn_off
      entity_id: light.btf_pixel_strip_top

# ##################################
# Hall Small-  Main Lamp (Xiaomi Round LED) - On
# ##################################
- alias: hall_small_main_lamp_on
  initial_state: 'true'
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.0x4cf8cdf3c7a9a48_action
      to: 'button_1_single'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.round_led_hs
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.round_led_hs
        - conditions:
            - condition: state
              entity_id: light.round_led_hs
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.round_led_hs
              data_template:
                brightness_pct: 30
                kelvin: 5000

# ##################################
# Hall Small-  Main Lamp (Xiaomi Round LED) - Double
# ##################################
- alias: hall_small_main_lamp_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x4cf8cdf3c7a9a48_action
      to: 'button_1_double'
  action:
    - service: light.turn_on
      entity_id: light.round_led_hs
      data_template:
        brightness_pct: 100
        kelvin: 5000
        
# ##################################
# Hall Small - Main Lamp Reset 
# ##################################
- alias: hall_small_main_lamp_reset
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: light.round_led_hs
      state: 'unavailable'
      for:
        minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.round_led_hs_restart